### ISSUE TITLE
Some footprints missing REF** on F.Fab layer

### ISSUE THREAD

**Issue by jensenr30** [KiCad/Potentiometers.pretty#20]
I noticed that this footprint does not have a reference designator on the F.Fab layer.
Potentiometer_Trimmer_Bourns_3296W.kicad_mod
I'm assuming that nobody has noticed or bothered to fix it.
I would guess that there are a lot footprints in this library that are lacking reference designators on the F.Fab layer.
If nobody else fixes this, I will try to get around to checking all the footprints and fixing them eventually.

**Comment by SchrodingersGat** [comment]
There are probably heaps! (Especially the non scripted ones).

The second RefDes is a recently new requirement, so not all the footprints are compliant.

It would be worth checking the scripts to see if a particular set of footprints have been scripted before you spend any time fixing them manually :) Even if it means someone else needs to update the scripts.

**Comment by evanshultz** [comment]
Resolved with https://github.com/KiCad/kicad-footprints/pull/190.
